[alias]
release-linux-x86-64 = "build --locked --release --target x86_64-unknown-linux-gnu"
release-linux-arm64 = "build --locked --release --target aarch64-unknown-linux-gnu"
release-windows-x86-64 = "build --locked --release --target x86_64-pc-windows-msvc"
release-windows-arm64 = "build --locked --release --target aarch64-pc-windows-msvc"
release-macos-arm64 = "build --locked --release --target aarch64-apple-darwin"
